// AUTO-GENERATED BY gen_lua_bindings.py - DO NOT EDIT
// Generated by the SBLT build for inclusion in the plugin SDK.

#include "lua.h"
#include "lauxlib.h"

struct LuaPluginFunctionTable {
    lua_State* (*lua_newstate)(lua_Alloc f, void* ud);
    void (*lua_close)(lua_State* L);
    lua_State* (*lua_newthread)(lua_State* L);
    lua_CFunction (*lua_atpanic)(lua_State* L, lua_CFunction panicf);
    int (*lua_gettop)(lua_State* L);
    void (*lua_settop)(lua_State* L, int idx);
    void (*lua_pushvalue)(lua_State* L, int idx);
    void (*lua_remove)(lua_State* L, int idx);
    void (*lua_insert)(lua_State* L, int idx);
    void (*lua_replace)(lua_State* L, int idx);
    int (*lua_checkstack)(lua_State* L, int sz);
    void (*lua_xmove)(lua_State* from, lua_State* to, int n);
    int (*lua_isnumber)(lua_State* L, int idx);
    int (*lua_isstring)(lua_State* L, int idx);
    int (*lua_iscfunction)(lua_State* L, int idx);
    int (*lua_isuserdata)(lua_State* L, int idx);
    int (*lua_type)(lua_State* L, int idx);
    const char* (*lua_typename)(lua_State* L, int tp);
    int (*lua_equal)(lua_State* L, int idx1, int idx2);
    int (*lua_rawequal)(lua_State* L, int idx1, int idx2);
    int (*lua_lessthan)(lua_State* L, int idx1, int idx2);
    lua_Number (*lua_tonumber)(lua_State* L, int idx);
    lua_Integer (*lua_tointeger)(lua_State* L, int idx);
    int (*lua_toboolean)(lua_State* L, int idx);
    const char* (*lua_tolstring)(lua_State* L, int idx, size_t* len);
    size_t (*lua_objlen)(lua_State* L, int idx);
    lua_CFunction (*lua_tocfunction)(lua_State* L, int idx);
    void* (*lua_touserdata)(lua_State* L, int idx);
    lua_State* (*lua_tothread)(lua_State* L, int idx);
    const void* (*lua_topointer)(lua_State* L, int idx);
    void (*lua_pushnil)(lua_State* L);
    void (*lua_pushnumber)(lua_State* L, lua_Number n);
    void (*lua_pushinteger)(lua_State* L, lua_Integer n);
    void (*lua_pushlstring)(lua_State* L, const char* s, size_t l);
    void (*lua_pushstring)(lua_State* L, const char* s);
    const char* (*lua_pushvfstring)(lua_State* L, const char* fmt, va_list argp);
    const char* (*lua_pushfstring)(lua_State* L, const char* fmt);
    void (*lua_pushcclosure)(lua_State* L, lua_CFunction fn, int n);
    void (*lua_pushboolean)(lua_State* L, int b);
    void (*lua_pushlightuserdata)(lua_State* L, void* p);
    int (*lua_pushthread)(lua_State* L);
    void (*lua_gettable)(lua_State* L, int idx);
    void (*lua_getfield)(lua_State* L, int idx, const char* k);
    void (*lua_rawget)(lua_State* L, int idx);
    void (*lua_rawgeti)(lua_State* L, int idx, int n);
    void (*lua_createtable)(lua_State* L, int narr, int nrec);
    void* (*lua_newuserdata)(lua_State* L, size_t sz);
    int (*lua_getmetatable)(lua_State* L, int objindex);
    void (*lua_getfenv)(lua_State* L, int idx);
    void (*lua_settable)(lua_State* L, int idx);
    void (*lua_setfield)(lua_State* L, int idx, const char* k);
    void (*lua_rawset)(lua_State* L, int idx);
    void (*lua_rawseti)(lua_State* L, int idx, int n);
    int (*lua_setmetatable)(lua_State* L, int objindex);
    int (*lua_setfenv)(lua_State* L, int idx);
    void (*lua_call)(lua_State* L, int nargs, int nresults);
    int (*lua_pcall)(lua_State* L, int nargs, int nresults, int errfunc);
    int (*lua_cpcall)(lua_State* L, lua_CFunction func, void* ud);
    int (*lua_load)(lua_State* L, lua_Reader reader, void* dt, const char* chunkname);
    int (*lua_dump)(lua_State* L, lua_Writer writer, void* data);
    int (*lua_yield)(lua_State* L, int nresults);
    int (*lua_resume)(lua_State* L, int narg);
    int (*lua_status)(lua_State* L);
    int (*lua_gc)(lua_State* L, int what, int data);
    int (*lua_error)(lua_State* L);
    int (*lua_next)(lua_State* L, int idx);
    void (*lua_concat)(lua_State* L, int n);
    lua_Alloc (*lua_getallocf)(lua_State* L, void** ud);
    void (*lua_setallocf)(lua_State* L, lua_Alloc f, void* ud);
    int (*lua_getstack)(lua_State* L, int level, lua_Debug* ar);
    int (*lua_getinfo)(lua_State* L, const char* what, lua_Debug* ar);
    const char* (*lua_getlocal)(lua_State* L, const lua_Debug* ar, int n);
    const char* (*lua_setlocal)(lua_State* L, const lua_Debug* ar, int n);
    const char* (*lua_getupvalue)(lua_State* L, int funcindex, int n);
    const char* (*lua_setupvalue)(lua_State* L, int funcindex, int n);
    int (*lua_sethook)(lua_State* L, lua_Hook func, int mask, int count);
    lua_Hook (*lua_gethook)(lua_State* L);
    int (*lua_gethookmask)(lua_State* L);
    int (*lua_gethookcount)(lua_State* L);
    void* (*lua_upvalueid)(lua_State* L, int idx, int n);
    void (*lua_upvaluejoin)(lua_State* L, int idx1, int n1, int idx2, int n2);
    int (*lua_loadx)(lua_State* L, lua_Reader reader, void* dt, const char* chunkname, const char* mode);
    const lua_Number* (*lua_version)(lua_State* L);
    void (*lua_copy)(lua_State* L, int fromidx, int toidx);
    lua_Number (*lua_tonumberx)(lua_State* L, int idx, int* isnum);
    lua_Integer (*lua_tointegerx)(lua_State* L, int idx, int* isnum);
    int (*lua_isyieldable)(lua_State* L);
    void (*luaL_openlib)(lua_State* L, const char* libname, const luaL_Reg* l, int nup);
    void (*luaL_register)(lua_State* L, const char* libname, const luaL_Reg* l);
    int (*luaL_getmetafield)(lua_State* L, int obj, const char* e);
    int (*luaL_callmeta)(lua_State* L, int obj, const char* e);
    int (*luaL_typerror)(lua_State* L, int narg, const char* tname);
    int (*luaL_argerror)(lua_State* L, int numarg, const char* extramsg);
    const char* (*luaL_checklstring)(lua_State* L, int numArg, size_t* l);
    const char* (*luaL_optlstring)(lua_State* L, int numArg, const char* def, size_t* l);
    lua_Number (*luaL_checknumber)(lua_State* L, int numArg);
    lua_Number (*luaL_optnumber)(lua_State* L, int nArg, lua_Number def);
    lua_Integer (*luaL_checkinteger)(lua_State* L, int numArg);
    lua_Integer (*luaL_optinteger)(lua_State* L, int nArg, lua_Integer def);
    void (*luaL_checkstack)(lua_State* L, int sz, const char* msg);
    void (*luaL_checktype)(lua_State* L, int narg, int t);
    void (*luaL_checkany)(lua_State* L, int narg);
    int (*luaL_newmetatable)(lua_State* L, const char* tname);
    void* (*luaL_checkudata)(lua_State* L, int ud, const char* tname);
    void (*luaL_where)(lua_State* L, int lvl);
    int (*luaL_error)(lua_State* L, const char* fmt);
    int (*luaL_ref)(lua_State* L, int t);
    void (*luaL_unref)(lua_State* L, int t, int ref);
    int (*luaL_loadfile)(lua_State* L, const char* filename);
    int (*luaL_loadbuffer)(lua_State* L, const char* buff, size_t sz, const char* name);
    int (*luaL_loadstring)(lua_State* L, const char* s);
    lua_State* (*luaL_newstate)();
    const char* (*luaL_gsub)(lua_State* L, const char* s, const char* p, const char* r);
    const char* (*luaL_findtable)(lua_State* L, int idx, const char* fname, int szhint);
    int (*luaL_fileresult)(lua_State* L, int stat, const char* fname);
    int (*luaL_execresult)(lua_State* L, int stat);
    int (*luaL_loadfilex)(lua_State* L, const char* filename, const char* mode);
    int (*luaL_loadbufferx)(lua_State* L, const char* buff, size_t sz, const char* name, const char* mode);
    void (*luaL_traceback)(lua_State* L, lua_State* L1, const char* msg, int level);
    void (*luaL_setfuncs)(lua_State* L, const luaL_Reg* l, int nup);
    void (*luaL_pushmodule)(lua_State* L, const char* modname, int sizehint);
    void* (*luaL_testudata)(lua_State* L, int ud, const char* tname);
    void (*luaL_setmetatable)(lua_State* L, const char* tname);
    void (*luaL_buffinit)(lua_State* L, luaL_Buffer* B);
    char* (*luaL_prepbuffer)(luaL_Buffer* B);
    void (*luaL_addlstring)(luaL_Buffer* B, const char* s, size_t l);
    void (*luaL_addstring)(luaL_Buffer* B, const char* s);
    void (*luaL_addvalue)(luaL_Buffer* B);
    void (*luaL_pushresult)(luaL_Buffer* B);

} LUA_FUNCTION_TABLE = {};

void SBLT_LUA_INIT_FUNC_TABLE(void* (*loadFn)(const char*)) {
    LUA_FUNCTION_TABLE.lua_newstate = (decltype(LUA_FUNCTION_TABLE.lua_newstate)) loadFn("lua_newstate");
    LUA_FUNCTION_TABLE.lua_close = (decltype(LUA_FUNCTION_TABLE.lua_close)) loadFn("lua_close");
    LUA_FUNCTION_TABLE.lua_newthread = (decltype(LUA_FUNCTION_TABLE.lua_newthread)) loadFn("lua_newthread");
    LUA_FUNCTION_TABLE.lua_atpanic = (decltype(LUA_FUNCTION_TABLE.lua_atpanic)) loadFn("lua_atpanic");
    LUA_FUNCTION_TABLE.lua_gettop = (decltype(LUA_FUNCTION_TABLE.lua_gettop)) loadFn("lua_gettop");
    LUA_FUNCTION_TABLE.lua_settop = (decltype(LUA_FUNCTION_TABLE.lua_settop)) loadFn("lua_settop");
    LUA_FUNCTION_TABLE.lua_pushvalue = (decltype(LUA_FUNCTION_TABLE.lua_pushvalue)) loadFn("lua_pushvalue");
    LUA_FUNCTION_TABLE.lua_remove = (decltype(LUA_FUNCTION_TABLE.lua_remove)) loadFn("lua_remove");
    LUA_FUNCTION_TABLE.lua_insert = (decltype(LUA_FUNCTION_TABLE.lua_insert)) loadFn("lua_insert");
    LUA_FUNCTION_TABLE.lua_replace = (decltype(LUA_FUNCTION_TABLE.lua_replace)) loadFn("lua_replace");
    LUA_FUNCTION_TABLE.lua_checkstack = (decltype(LUA_FUNCTION_TABLE.lua_checkstack)) loadFn("lua_checkstack");
    LUA_FUNCTION_TABLE.lua_xmove = (decltype(LUA_FUNCTION_TABLE.lua_xmove)) loadFn("lua_xmove");
    LUA_FUNCTION_TABLE.lua_isnumber = (decltype(LUA_FUNCTION_TABLE.lua_isnumber)) loadFn("lua_isnumber");
    LUA_FUNCTION_TABLE.lua_isstring = (decltype(LUA_FUNCTION_TABLE.lua_isstring)) loadFn("lua_isstring");
    LUA_FUNCTION_TABLE.lua_iscfunction = (decltype(LUA_FUNCTION_TABLE.lua_iscfunction)) loadFn("lua_iscfunction");
    LUA_FUNCTION_TABLE.lua_isuserdata = (decltype(LUA_FUNCTION_TABLE.lua_isuserdata)) loadFn("lua_isuserdata");
    LUA_FUNCTION_TABLE.lua_type = (decltype(LUA_FUNCTION_TABLE.lua_type)) loadFn("lua_type");
    LUA_FUNCTION_TABLE.lua_typename = (decltype(LUA_FUNCTION_TABLE.lua_typename)) loadFn("lua_typename");
    LUA_FUNCTION_TABLE.lua_equal = (decltype(LUA_FUNCTION_TABLE.lua_equal)) loadFn("lua_equal");
    LUA_FUNCTION_TABLE.lua_rawequal = (decltype(LUA_FUNCTION_TABLE.lua_rawequal)) loadFn("lua_rawequal");
    LUA_FUNCTION_TABLE.lua_lessthan = (decltype(LUA_FUNCTION_TABLE.lua_lessthan)) loadFn("lua_lessthan");
    LUA_FUNCTION_TABLE.lua_tonumber = (decltype(LUA_FUNCTION_TABLE.lua_tonumber)) loadFn("lua_tonumber");
    LUA_FUNCTION_TABLE.lua_tointeger = (decltype(LUA_FUNCTION_TABLE.lua_tointeger)) loadFn("lua_tointeger");
    LUA_FUNCTION_TABLE.lua_toboolean = (decltype(LUA_FUNCTION_TABLE.lua_toboolean)) loadFn("lua_toboolean");
    LUA_FUNCTION_TABLE.lua_tolstring = (decltype(LUA_FUNCTION_TABLE.lua_tolstring)) loadFn("lua_tolstring");
    LUA_FUNCTION_TABLE.lua_objlen = (decltype(LUA_FUNCTION_TABLE.lua_objlen)) loadFn("lua_objlen");
    LUA_FUNCTION_TABLE.lua_tocfunction = (decltype(LUA_FUNCTION_TABLE.lua_tocfunction)) loadFn("lua_tocfunction");
    LUA_FUNCTION_TABLE.lua_touserdata = (decltype(LUA_FUNCTION_TABLE.lua_touserdata)) loadFn("lua_touserdata");
    LUA_FUNCTION_TABLE.lua_tothread = (decltype(LUA_FUNCTION_TABLE.lua_tothread)) loadFn("lua_tothread");
    LUA_FUNCTION_TABLE.lua_topointer = (decltype(LUA_FUNCTION_TABLE.lua_topointer)) loadFn("lua_topointer");
    LUA_FUNCTION_TABLE.lua_pushnil = (decltype(LUA_FUNCTION_TABLE.lua_pushnil)) loadFn("lua_pushnil");
    LUA_FUNCTION_TABLE.lua_pushnumber = (decltype(LUA_FUNCTION_TABLE.lua_pushnumber)) loadFn("lua_pushnumber");
    LUA_FUNCTION_TABLE.lua_pushinteger = (decltype(LUA_FUNCTION_TABLE.lua_pushinteger)) loadFn("lua_pushinteger");
    LUA_FUNCTION_TABLE.lua_pushlstring = (decltype(LUA_FUNCTION_TABLE.lua_pushlstring)) loadFn("lua_pushlstring");
    LUA_FUNCTION_TABLE.lua_pushstring = (decltype(LUA_FUNCTION_TABLE.lua_pushstring)) loadFn("lua_pushstring");
    LUA_FUNCTION_TABLE.lua_pushvfstring = (decltype(LUA_FUNCTION_TABLE.lua_pushvfstring)) loadFn("lua_pushvfstring");
    LUA_FUNCTION_TABLE.lua_pushfstring = (decltype(LUA_FUNCTION_TABLE.lua_pushfstring)) loadFn("lua_pushfstring");
    LUA_FUNCTION_TABLE.lua_pushcclosure = (decltype(LUA_FUNCTION_TABLE.lua_pushcclosure)) loadFn("lua_pushcclosure");
    LUA_FUNCTION_TABLE.lua_pushboolean = (decltype(LUA_FUNCTION_TABLE.lua_pushboolean)) loadFn("lua_pushboolean");
    LUA_FUNCTION_TABLE.lua_pushlightuserdata = (decltype(LUA_FUNCTION_TABLE.lua_pushlightuserdata)) loadFn("lua_pushlightuserdata");
    LUA_FUNCTION_TABLE.lua_pushthread = (decltype(LUA_FUNCTION_TABLE.lua_pushthread)) loadFn("lua_pushthread");
    LUA_FUNCTION_TABLE.lua_gettable = (decltype(LUA_FUNCTION_TABLE.lua_gettable)) loadFn("lua_gettable");
    LUA_FUNCTION_TABLE.lua_getfield = (decltype(LUA_FUNCTION_TABLE.lua_getfield)) loadFn("lua_getfield");
    LUA_FUNCTION_TABLE.lua_rawget = (decltype(LUA_FUNCTION_TABLE.lua_rawget)) loadFn("lua_rawget");
    LUA_FUNCTION_TABLE.lua_rawgeti = (decltype(LUA_FUNCTION_TABLE.lua_rawgeti)) loadFn("lua_rawgeti");
    LUA_FUNCTION_TABLE.lua_createtable = (decltype(LUA_FUNCTION_TABLE.lua_createtable)) loadFn("lua_createtable");
    LUA_FUNCTION_TABLE.lua_newuserdata = (decltype(LUA_FUNCTION_TABLE.lua_newuserdata)) loadFn("lua_newuserdata");
    LUA_FUNCTION_TABLE.lua_getmetatable = (decltype(LUA_FUNCTION_TABLE.lua_getmetatable)) loadFn("lua_getmetatable");
    LUA_FUNCTION_TABLE.lua_getfenv = (decltype(LUA_FUNCTION_TABLE.lua_getfenv)) loadFn("lua_getfenv");
    LUA_FUNCTION_TABLE.lua_settable = (decltype(LUA_FUNCTION_TABLE.lua_settable)) loadFn("lua_settable");
    LUA_FUNCTION_TABLE.lua_setfield = (decltype(LUA_FUNCTION_TABLE.lua_setfield)) loadFn("lua_setfield");
    LUA_FUNCTION_TABLE.lua_rawset = (decltype(LUA_FUNCTION_TABLE.lua_rawset)) loadFn("lua_rawset");
    LUA_FUNCTION_TABLE.lua_rawseti = (decltype(LUA_FUNCTION_TABLE.lua_rawseti)) loadFn("lua_rawseti");
    LUA_FUNCTION_TABLE.lua_setmetatable = (decltype(LUA_FUNCTION_TABLE.lua_setmetatable)) loadFn("lua_setmetatable");
    LUA_FUNCTION_TABLE.lua_setfenv = (decltype(LUA_FUNCTION_TABLE.lua_setfenv)) loadFn("lua_setfenv");
    LUA_FUNCTION_TABLE.lua_call = (decltype(LUA_FUNCTION_TABLE.lua_call)) loadFn("lua_call");
    LUA_FUNCTION_TABLE.lua_pcall = (decltype(LUA_FUNCTION_TABLE.lua_pcall)) loadFn("lua_pcall");
    LUA_FUNCTION_TABLE.lua_cpcall = (decltype(LUA_FUNCTION_TABLE.lua_cpcall)) loadFn("lua_cpcall");
    LUA_FUNCTION_TABLE.lua_load = (decltype(LUA_FUNCTION_TABLE.lua_load)) loadFn("lua_load");
    LUA_FUNCTION_TABLE.lua_dump = (decltype(LUA_FUNCTION_TABLE.lua_dump)) loadFn("lua_dump");
    LUA_FUNCTION_TABLE.lua_yield = (decltype(LUA_FUNCTION_TABLE.lua_yield)) loadFn("lua_yield");
    LUA_FUNCTION_TABLE.lua_resume = (decltype(LUA_FUNCTION_TABLE.lua_resume)) loadFn("lua_resume");
    LUA_FUNCTION_TABLE.lua_status = (decltype(LUA_FUNCTION_TABLE.lua_status)) loadFn("lua_status");
    LUA_FUNCTION_TABLE.lua_gc = (decltype(LUA_FUNCTION_TABLE.lua_gc)) loadFn("lua_gc");
    LUA_FUNCTION_TABLE.lua_error = (decltype(LUA_FUNCTION_TABLE.lua_error)) loadFn("lua_error");
    LUA_FUNCTION_TABLE.lua_next = (decltype(LUA_FUNCTION_TABLE.lua_next)) loadFn("lua_next");
    LUA_FUNCTION_TABLE.lua_concat = (decltype(LUA_FUNCTION_TABLE.lua_concat)) loadFn("lua_concat");
    LUA_FUNCTION_TABLE.lua_getallocf = (decltype(LUA_FUNCTION_TABLE.lua_getallocf)) loadFn("lua_getallocf");
    LUA_FUNCTION_TABLE.lua_setallocf = (decltype(LUA_FUNCTION_TABLE.lua_setallocf)) loadFn("lua_setallocf");
    LUA_FUNCTION_TABLE.lua_getstack = (decltype(LUA_FUNCTION_TABLE.lua_getstack)) loadFn("lua_getstack");
    LUA_FUNCTION_TABLE.lua_getinfo = (decltype(LUA_FUNCTION_TABLE.lua_getinfo)) loadFn("lua_getinfo");
    LUA_FUNCTION_TABLE.lua_getlocal = (decltype(LUA_FUNCTION_TABLE.lua_getlocal)) loadFn("lua_getlocal");
    LUA_FUNCTION_TABLE.lua_setlocal = (decltype(LUA_FUNCTION_TABLE.lua_setlocal)) loadFn("lua_setlocal");
    LUA_FUNCTION_TABLE.lua_getupvalue = (decltype(LUA_FUNCTION_TABLE.lua_getupvalue)) loadFn("lua_getupvalue");
    LUA_FUNCTION_TABLE.lua_setupvalue = (decltype(LUA_FUNCTION_TABLE.lua_setupvalue)) loadFn("lua_setupvalue");
    LUA_FUNCTION_TABLE.lua_sethook = (decltype(LUA_FUNCTION_TABLE.lua_sethook)) loadFn("lua_sethook");
    LUA_FUNCTION_TABLE.lua_gethook = (decltype(LUA_FUNCTION_TABLE.lua_gethook)) loadFn("lua_gethook");
    LUA_FUNCTION_TABLE.lua_gethookmask = (decltype(LUA_FUNCTION_TABLE.lua_gethookmask)) loadFn("lua_gethookmask");
    LUA_FUNCTION_TABLE.lua_gethookcount = (decltype(LUA_FUNCTION_TABLE.lua_gethookcount)) loadFn("lua_gethookcount");
    LUA_FUNCTION_TABLE.lua_upvalueid = (decltype(LUA_FUNCTION_TABLE.lua_upvalueid)) loadFn("lua_upvalueid");
    LUA_FUNCTION_TABLE.lua_upvaluejoin = (decltype(LUA_FUNCTION_TABLE.lua_upvaluejoin)) loadFn("lua_upvaluejoin");
    LUA_FUNCTION_TABLE.lua_loadx = (decltype(LUA_FUNCTION_TABLE.lua_loadx)) loadFn("lua_loadx");
    LUA_FUNCTION_TABLE.lua_version = (decltype(LUA_FUNCTION_TABLE.lua_version)) loadFn("lua_version");
    LUA_FUNCTION_TABLE.lua_copy = (decltype(LUA_FUNCTION_TABLE.lua_copy)) loadFn("lua_copy");
    LUA_FUNCTION_TABLE.lua_tonumberx = (decltype(LUA_FUNCTION_TABLE.lua_tonumberx)) loadFn("lua_tonumberx");
    LUA_FUNCTION_TABLE.lua_tointegerx = (decltype(LUA_FUNCTION_TABLE.lua_tointegerx)) loadFn("lua_tointegerx");
    LUA_FUNCTION_TABLE.lua_isyieldable = (decltype(LUA_FUNCTION_TABLE.lua_isyieldable)) loadFn("lua_isyieldable");
    LUA_FUNCTION_TABLE.luaL_openlib = (decltype(LUA_FUNCTION_TABLE.luaL_openlib)) loadFn("luaL_openlib");
    LUA_FUNCTION_TABLE.luaL_register = (decltype(LUA_FUNCTION_TABLE.luaL_register)) loadFn("luaL_register");
    LUA_FUNCTION_TABLE.luaL_getmetafield = (decltype(LUA_FUNCTION_TABLE.luaL_getmetafield)) loadFn("luaL_getmetafield");
    LUA_FUNCTION_TABLE.luaL_callmeta = (decltype(LUA_FUNCTION_TABLE.luaL_callmeta)) loadFn("luaL_callmeta");
    LUA_FUNCTION_TABLE.luaL_typerror = (decltype(LUA_FUNCTION_TABLE.luaL_typerror)) loadFn("luaL_typerror");
    LUA_FUNCTION_TABLE.luaL_argerror = (decltype(LUA_FUNCTION_TABLE.luaL_argerror)) loadFn("luaL_argerror");
    LUA_FUNCTION_TABLE.luaL_checklstring = (decltype(LUA_FUNCTION_TABLE.luaL_checklstring)) loadFn("luaL_checklstring");
    LUA_FUNCTION_TABLE.luaL_optlstring = (decltype(LUA_FUNCTION_TABLE.luaL_optlstring)) loadFn("luaL_optlstring");
    LUA_FUNCTION_TABLE.luaL_checknumber = (decltype(LUA_FUNCTION_TABLE.luaL_checknumber)) loadFn("luaL_checknumber");
    LUA_FUNCTION_TABLE.luaL_optnumber = (decltype(LUA_FUNCTION_TABLE.luaL_optnumber)) loadFn("luaL_optnumber");
    LUA_FUNCTION_TABLE.luaL_checkinteger = (decltype(LUA_FUNCTION_TABLE.luaL_checkinteger)) loadFn("luaL_checkinteger");
    LUA_FUNCTION_TABLE.luaL_optinteger = (decltype(LUA_FUNCTION_TABLE.luaL_optinteger)) loadFn("luaL_optinteger");
    LUA_FUNCTION_TABLE.luaL_checkstack = (decltype(LUA_FUNCTION_TABLE.luaL_checkstack)) loadFn("luaL_checkstack");
    LUA_FUNCTION_TABLE.luaL_checktype = (decltype(LUA_FUNCTION_TABLE.luaL_checktype)) loadFn("luaL_checktype");
    LUA_FUNCTION_TABLE.luaL_checkany = (decltype(LUA_FUNCTION_TABLE.luaL_checkany)) loadFn("luaL_checkany");
    LUA_FUNCTION_TABLE.luaL_newmetatable = (decltype(LUA_FUNCTION_TABLE.luaL_newmetatable)) loadFn("luaL_newmetatable");
    LUA_FUNCTION_TABLE.luaL_checkudata = (decltype(LUA_FUNCTION_TABLE.luaL_checkudata)) loadFn("luaL_checkudata");
    LUA_FUNCTION_TABLE.luaL_where = (decltype(LUA_FUNCTION_TABLE.luaL_where)) loadFn("luaL_where");
    LUA_FUNCTION_TABLE.luaL_error = (decltype(LUA_FUNCTION_TABLE.luaL_error)) loadFn("luaL_error");
    LUA_FUNCTION_TABLE.luaL_ref = (decltype(LUA_FUNCTION_TABLE.luaL_ref)) loadFn("luaL_ref");
    LUA_FUNCTION_TABLE.luaL_unref = (decltype(LUA_FUNCTION_TABLE.luaL_unref)) loadFn("luaL_unref");
    LUA_FUNCTION_TABLE.luaL_loadfile = (decltype(LUA_FUNCTION_TABLE.luaL_loadfile)) loadFn("luaL_loadfile");
    LUA_FUNCTION_TABLE.luaL_loadbuffer = (decltype(LUA_FUNCTION_TABLE.luaL_loadbuffer)) loadFn("luaL_loadbuffer");
    LUA_FUNCTION_TABLE.luaL_loadstring = (decltype(LUA_FUNCTION_TABLE.luaL_loadstring)) loadFn("luaL_loadstring");
    LUA_FUNCTION_TABLE.luaL_newstate = (decltype(LUA_FUNCTION_TABLE.luaL_newstate)) loadFn("luaL_newstate");
    LUA_FUNCTION_TABLE.luaL_gsub = (decltype(LUA_FUNCTION_TABLE.luaL_gsub)) loadFn("luaL_gsub");
    LUA_FUNCTION_TABLE.luaL_findtable = (decltype(LUA_FUNCTION_TABLE.luaL_findtable)) loadFn("luaL_findtable");
    LUA_FUNCTION_TABLE.luaL_fileresult = (decltype(LUA_FUNCTION_TABLE.luaL_fileresult)) loadFn("luaL_fileresult");
    LUA_FUNCTION_TABLE.luaL_execresult = (decltype(LUA_FUNCTION_TABLE.luaL_execresult)) loadFn("luaL_execresult");
    LUA_FUNCTION_TABLE.luaL_loadfilex = (decltype(LUA_FUNCTION_TABLE.luaL_loadfilex)) loadFn("luaL_loadfilex");
    LUA_FUNCTION_TABLE.luaL_loadbufferx = (decltype(LUA_FUNCTION_TABLE.luaL_loadbufferx)) loadFn("luaL_loadbufferx");
    LUA_FUNCTION_TABLE.luaL_traceback = (decltype(LUA_FUNCTION_TABLE.luaL_traceback)) loadFn("luaL_traceback");
    LUA_FUNCTION_TABLE.luaL_setfuncs = (decltype(LUA_FUNCTION_TABLE.luaL_setfuncs)) loadFn("luaL_setfuncs");
    LUA_FUNCTION_TABLE.luaL_pushmodule = (decltype(LUA_FUNCTION_TABLE.luaL_pushmodule)) loadFn("luaL_pushmodule");
    LUA_FUNCTION_TABLE.luaL_testudata = (decltype(LUA_FUNCTION_TABLE.luaL_testudata)) loadFn("luaL_testudata");
    LUA_FUNCTION_TABLE.luaL_setmetatable = (decltype(LUA_FUNCTION_TABLE.luaL_setmetatable)) loadFn("luaL_setmetatable");
    LUA_FUNCTION_TABLE.luaL_buffinit = (decltype(LUA_FUNCTION_TABLE.luaL_buffinit)) loadFn("luaL_buffinit");
    LUA_FUNCTION_TABLE.luaL_prepbuffer = (decltype(LUA_FUNCTION_TABLE.luaL_prepbuffer)) loadFn("luaL_prepbuffer");
    LUA_FUNCTION_TABLE.luaL_addlstring = (decltype(LUA_FUNCTION_TABLE.luaL_addlstring)) loadFn("luaL_addlstring");
    LUA_FUNCTION_TABLE.luaL_addstring = (decltype(LUA_FUNCTION_TABLE.luaL_addstring)) loadFn("luaL_addstring");
    LUA_FUNCTION_TABLE.luaL_addvalue = (decltype(LUA_FUNCTION_TABLE.luaL_addvalue)) loadFn("luaL_addvalue");
    LUA_FUNCTION_TABLE.luaL_pushresult = (decltype(LUA_FUNCTION_TABLE.luaL_pushresult)) loadFn("luaL_pushresult");

}

lua_State* lua_newstate(lua_Alloc f, void* ud) {
    return LUA_FUNCTION_TABLE.lua_newstate(f, ud);
}
void lua_close(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_close(L);
}
lua_State* lua_newthread(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_newthread(L);
}
lua_CFunction lua_atpanic(lua_State* L, lua_CFunction panicf) {
    return LUA_FUNCTION_TABLE.lua_atpanic(L, panicf);
}
int lua_gettop(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_gettop(L);
}
void lua_settop(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_settop(L, idx);
}
void lua_pushvalue(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_pushvalue(L, idx);
}
void lua_remove(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_remove(L, idx);
}
void lua_insert(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_insert(L, idx);
}
void lua_replace(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_replace(L, idx);
}
int lua_checkstack(lua_State* L, int sz) {
    return LUA_FUNCTION_TABLE.lua_checkstack(L, sz);
}
void lua_xmove(lua_State* from, lua_State* to, int n) {
    return LUA_FUNCTION_TABLE.lua_xmove(from, to, n);
}
int lua_isnumber(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_isnumber(L, idx);
}
int lua_isstring(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_isstring(L, idx);
}
int lua_iscfunction(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_iscfunction(L, idx);
}
int lua_isuserdata(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_isuserdata(L, idx);
}
int lua_type(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_type(L, idx);
}
const char* lua_typename(lua_State* L, int tp) {
    return LUA_FUNCTION_TABLE.lua_typename(L, tp);
}
int lua_equal(lua_State* L, int idx1, int idx2) {
    return LUA_FUNCTION_TABLE.lua_equal(L, idx1, idx2);
}
int lua_rawequal(lua_State* L, int idx1, int idx2) {
    return LUA_FUNCTION_TABLE.lua_rawequal(L, idx1, idx2);
}
int lua_lessthan(lua_State* L, int idx1, int idx2) {
    return LUA_FUNCTION_TABLE.lua_lessthan(L, idx1, idx2);
}
lua_Number lua_tonumber(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_tonumber(L, idx);
}
lua_Integer lua_tointeger(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_tointeger(L, idx);
}
int lua_toboolean(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_toboolean(L, idx);
}
const char* lua_tolstring(lua_State* L, int idx, size_t* len) {
    return LUA_FUNCTION_TABLE.lua_tolstring(L, idx, len);
}
size_t lua_objlen(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_objlen(L, idx);
}
lua_CFunction lua_tocfunction(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_tocfunction(L, idx);
}
void* lua_touserdata(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_touserdata(L, idx);
}
lua_State* lua_tothread(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_tothread(L, idx);
}
const void* lua_topointer(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_topointer(L, idx);
}
void lua_pushnil(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_pushnil(L);
}
void lua_pushnumber(lua_State* L, lua_Number n) {
    return LUA_FUNCTION_TABLE.lua_pushnumber(L, n);
}
void lua_pushinteger(lua_State* L, lua_Integer n) {
    return LUA_FUNCTION_TABLE.lua_pushinteger(L, n);
}
void lua_pushlstring(lua_State* L, const char* s, size_t l) {
    return LUA_FUNCTION_TABLE.lua_pushlstring(L, s, l);
}
void lua_pushstring(lua_State* L, const char* s) {
    return LUA_FUNCTION_TABLE.lua_pushstring(L, s);
}
const char* lua_pushvfstring(lua_State* L, const char* fmt, va_list argp) {
    return LUA_FUNCTION_TABLE.lua_pushvfstring(L, fmt, argp);
}
const char* lua_pushfstring(lua_State* L, const char* fmt) {
    return LUA_FUNCTION_TABLE.lua_pushfstring(L, fmt);
}
void lua_pushcclosure(lua_State* L, lua_CFunction fn, int n) {
    return LUA_FUNCTION_TABLE.lua_pushcclosure(L, fn, n);
}
void lua_pushboolean(lua_State* L, int b) {
    return LUA_FUNCTION_TABLE.lua_pushboolean(L, b);
}
void lua_pushlightuserdata(lua_State* L, void* p) {
    return LUA_FUNCTION_TABLE.lua_pushlightuserdata(L, p);
}
int lua_pushthread(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_pushthread(L);
}
void lua_gettable(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_gettable(L, idx);
}
void lua_getfield(lua_State* L, int idx, const char* k) {
    return LUA_FUNCTION_TABLE.lua_getfield(L, idx, k);
}
void lua_rawget(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_rawget(L, idx);
}
void lua_rawgeti(lua_State* L, int idx, int n) {
    return LUA_FUNCTION_TABLE.lua_rawgeti(L, idx, n);
}
void lua_createtable(lua_State* L, int narr, int nrec) {
    return LUA_FUNCTION_TABLE.lua_createtable(L, narr, nrec);
}
void* lua_newuserdata(lua_State* L, size_t sz) {
    return LUA_FUNCTION_TABLE.lua_newuserdata(L, sz);
}
int lua_getmetatable(lua_State* L, int objindex) {
    return LUA_FUNCTION_TABLE.lua_getmetatable(L, objindex);
}
void lua_getfenv(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_getfenv(L, idx);
}
void lua_settable(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_settable(L, idx);
}
void lua_setfield(lua_State* L, int idx, const char* k) {
    return LUA_FUNCTION_TABLE.lua_setfield(L, idx, k);
}
void lua_rawset(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_rawset(L, idx);
}
void lua_rawseti(lua_State* L, int idx, int n) {
    return LUA_FUNCTION_TABLE.lua_rawseti(L, idx, n);
}
int lua_setmetatable(lua_State* L, int objindex) {
    return LUA_FUNCTION_TABLE.lua_setmetatable(L, objindex);
}
int lua_setfenv(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_setfenv(L, idx);
}
void lua_call(lua_State* L, int nargs, int nresults) {
    return LUA_FUNCTION_TABLE.lua_call(L, nargs, nresults);
}
int lua_pcall(lua_State* L, int nargs, int nresults, int errfunc) {
    return LUA_FUNCTION_TABLE.lua_pcall(L, nargs, nresults, errfunc);
}
int lua_cpcall(lua_State* L, lua_CFunction func, void* ud) {
    return LUA_FUNCTION_TABLE.lua_cpcall(L, func, ud);
}
int lua_load(lua_State* L, lua_Reader reader, void* dt, const char* chunkname) {
    return LUA_FUNCTION_TABLE.lua_load(L, reader, dt, chunkname);
}
int lua_dump(lua_State* L, lua_Writer writer, void* data) {
    return LUA_FUNCTION_TABLE.lua_dump(L, writer, data);
}
int lua_yield(lua_State* L, int nresults) {
    return LUA_FUNCTION_TABLE.lua_yield(L, nresults);
}
int lua_resume(lua_State* L, int narg) {
    return LUA_FUNCTION_TABLE.lua_resume(L, narg);
}
int lua_status(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_status(L);
}
int lua_gc(lua_State* L, int what, int data) {
    return LUA_FUNCTION_TABLE.lua_gc(L, what, data);
}
int lua_error(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_error(L);
}
int lua_next(lua_State* L, int idx) {
    return LUA_FUNCTION_TABLE.lua_next(L, idx);
}
void lua_concat(lua_State* L, int n) {
    return LUA_FUNCTION_TABLE.lua_concat(L, n);
}
lua_Alloc lua_getallocf(lua_State* L, void** ud) {
    return LUA_FUNCTION_TABLE.lua_getallocf(L, ud);
}
void lua_setallocf(lua_State* L, lua_Alloc f, void* ud) {
    return LUA_FUNCTION_TABLE.lua_setallocf(L, f, ud);
}
int lua_getstack(lua_State* L, int level, lua_Debug* ar) {
    return LUA_FUNCTION_TABLE.lua_getstack(L, level, ar);
}
int lua_getinfo(lua_State* L, const char* what, lua_Debug* ar) {
    return LUA_FUNCTION_TABLE.lua_getinfo(L, what, ar);
}
const char* lua_getlocal(lua_State* L, const lua_Debug* ar, int n) {
    return LUA_FUNCTION_TABLE.lua_getlocal(L, ar, n);
}
const char* lua_setlocal(lua_State* L, const lua_Debug* ar, int n) {
    return LUA_FUNCTION_TABLE.lua_setlocal(L, ar, n);
}
const char* lua_getupvalue(lua_State* L, int funcindex, int n) {
    return LUA_FUNCTION_TABLE.lua_getupvalue(L, funcindex, n);
}
const char* lua_setupvalue(lua_State* L, int funcindex, int n) {
    return LUA_FUNCTION_TABLE.lua_setupvalue(L, funcindex, n);
}
int lua_sethook(lua_State* L, lua_Hook func, int mask, int count) {
    return LUA_FUNCTION_TABLE.lua_sethook(L, func, mask, count);
}
lua_Hook lua_gethook(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_gethook(L);
}
int lua_gethookmask(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_gethookmask(L);
}
int lua_gethookcount(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_gethookcount(L);
}
void* lua_upvalueid(lua_State* L, int idx, int n) {
    return LUA_FUNCTION_TABLE.lua_upvalueid(L, idx, n);
}
void lua_upvaluejoin(lua_State* L, int idx1, int n1, int idx2, int n2) {
    return LUA_FUNCTION_TABLE.lua_upvaluejoin(L, idx1, n1, idx2, n2);
}
int lua_loadx(lua_State* L, lua_Reader reader, void* dt, const char* chunkname, const char* mode) {
    return LUA_FUNCTION_TABLE.lua_loadx(L, reader, dt, chunkname, mode);
}
const lua_Number* lua_version(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_version(L);
}
void lua_copy(lua_State* L, int fromidx, int toidx) {
    return LUA_FUNCTION_TABLE.lua_copy(L, fromidx, toidx);
}
lua_Number lua_tonumberx(lua_State* L, int idx, int* isnum) {
    return LUA_FUNCTION_TABLE.lua_tonumberx(L, idx, isnum);
}
lua_Integer lua_tointegerx(lua_State* L, int idx, int* isnum) {
    return LUA_FUNCTION_TABLE.lua_tointegerx(L, idx, isnum);
}
int lua_isyieldable(lua_State* L) {
    return LUA_FUNCTION_TABLE.lua_isyieldable(L);
}
void luaL_openlib(lua_State* L, const char* libname, const luaL_Reg* l, int nup) {
    return LUA_FUNCTION_TABLE.luaL_openlib(L, libname, l, nup);
}
void luaL_register(lua_State* L, const char* libname, const luaL_Reg* l) {
    return LUA_FUNCTION_TABLE.luaL_register(L, libname, l);
}
int luaL_getmetafield(lua_State* L, int obj, const char* e) {
    return LUA_FUNCTION_TABLE.luaL_getmetafield(L, obj, e);
}
int luaL_callmeta(lua_State* L, int obj, const char* e) {
    return LUA_FUNCTION_TABLE.luaL_callmeta(L, obj, e);
}
int luaL_typerror(lua_State* L, int narg, const char* tname) {
    return LUA_FUNCTION_TABLE.luaL_typerror(L, narg, tname);
}
int luaL_argerror(lua_State* L, int numarg, const char* extramsg) {
    return LUA_FUNCTION_TABLE.luaL_argerror(L, numarg, extramsg);
}
const char* luaL_checklstring(lua_State* L, int numArg, size_t* l) {
    return LUA_FUNCTION_TABLE.luaL_checklstring(L, numArg, l);
}
const char* luaL_optlstring(lua_State* L, int numArg, const char* def, size_t* l) {
    return LUA_FUNCTION_TABLE.luaL_optlstring(L, numArg, def, l);
}
lua_Number luaL_checknumber(lua_State* L, int numArg) {
    return LUA_FUNCTION_TABLE.luaL_checknumber(L, numArg);
}
lua_Number luaL_optnumber(lua_State* L, int nArg, lua_Number def) {
    return LUA_FUNCTION_TABLE.luaL_optnumber(L, nArg, def);
}
lua_Integer luaL_checkinteger(lua_State* L, int numArg) {
    return LUA_FUNCTION_TABLE.luaL_checkinteger(L, numArg);
}
lua_Integer luaL_optinteger(lua_State* L, int nArg, lua_Integer def) {
    return LUA_FUNCTION_TABLE.luaL_optinteger(L, nArg, def);
}
void luaL_checkstack(lua_State* L, int sz, const char* msg) {
    return LUA_FUNCTION_TABLE.luaL_checkstack(L, sz, msg);
}
void luaL_checktype(lua_State* L, int narg, int t) {
    return LUA_FUNCTION_TABLE.luaL_checktype(L, narg, t);
}
void luaL_checkany(lua_State* L, int narg) {
    return LUA_FUNCTION_TABLE.luaL_checkany(L, narg);
}
int luaL_newmetatable(lua_State* L, const char* tname) {
    return LUA_FUNCTION_TABLE.luaL_newmetatable(L, tname);
}
void* luaL_checkudata(lua_State* L, int ud, const char* tname) {
    return LUA_FUNCTION_TABLE.luaL_checkudata(L, ud, tname);
}
void luaL_where(lua_State* L, int lvl) {
    return LUA_FUNCTION_TABLE.luaL_where(L, lvl);
}
int luaL_error(lua_State* L, const char* fmt) {
    return LUA_FUNCTION_TABLE.luaL_error(L, fmt);
}
int luaL_ref(lua_State* L, int t) {
    return LUA_FUNCTION_TABLE.luaL_ref(L, t);
}
void luaL_unref(lua_State* L, int t, int ref) {
    return LUA_FUNCTION_TABLE.luaL_unref(L, t, ref);
}
int luaL_loadfile(lua_State* L, const char* filename) {
    return LUA_FUNCTION_TABLE.luaL_loadfile(L, filename);
}
int luaL_loadbuffer(lua_State* L, const char* buff, size_t sz, const char* name) {
    return LUA_FUNCTION_TABLE.luaL_loadbuffer(L, buff, sz, name);
}
int luaL_loadstring(lua_State* L, const char* s) {
    return LUA_FUNCTION_TABLE.luaL_loadstring(L, s);
}
lua_State* luaL_newstate() {
    return LUA_FUNCTION_TABLE.luaL_newstate();
}
const char* luaL_gsub(lua_State* L, const char* s, const char* p, const char* r) {
    return LUA_FUNCTION_TABLE.luaL_gsub(L, s, p, r);
}
const char* luaL_findtable(lua_State* L, int idx, const char* fname, int szhint) {
    return LUA_FUNCTION_TABLE.luaL_findtable(L, idx, fname, szhint);
}
int luaL_fileresult(lua_State* L, int stat, const char* fname) {
    return LUA_FUNCTION_TABLE.luaL_fileresult(L, stat, fname);
}
int luaL_execresult(lua_State* L, int stat) {
    return LUA_FUNCTION_TABLE.luaL_execresult(L, stat);
}
int luaL_loadfilex(lua_State* L, const char* filename, const char* mode) {
    return LUA_FUNCTION_TABLE.luaL_loadfilex(L, filename, mode);
}
int luaL_loadbufferx(lua_State* L, const char* buff, size_t sz, const char* name, const char* mode) {
    return LUA_FUNCTION_TABLE.luaL_loadbufferx(L, buff, sz, name, mode);
}
void luaL_traceback(lua_State* L, lua_State* L1, const char* msg, int level) {
    return LUA_FUNCTION_TABLE.luaL_traceback(L, L1, msg, level);
}
void luaL_setfuncs(lua_State* L, const luaL_Reg* l, int nup) {
    return LUA_FUNCTION_TABLE.luaL_setfuncs(L, l, nup);
}
void luaL_pushmodule(lua_State* L, const char* modname, int sizehint) {
    return LUA_FUNCTION_TABLE.luaL_pushmodule(L, modname, sizehint);
}
void* luaL_testudata(lua_State* L, int ud, const char* tname) {
    return LUA_FUNCTION_TABLE.luaL_testudata(L, ud, tname);
}
void luaL_setmetatable(lua_State* L, const char* tname) {
    return LUA_FUNCTION_TABLE.luaL_setmetatable(L, tname);
}
void luaL_buffinit(lua_State* L, luaL_Buffer* B) {
    return LUA_FUNCTION_TABLE.luaL_buffinit(L, B);
}
char* luaL_prepbuffer(luaL_Buffer* B) {
    return LUA_FUNCTION_TABLE.luaL_prepbuffer(B);
}
void luaL_addlstring(luaL_Buffer* B, const char* s, size_t l) {
    return LUA_FUNCTION_TABLE.luaL_addlstring(B, s, l);
}
void luaL_addstring(luaL_Buffer* B, const char* s) {
    return LUA_FUNCTION_TABLE.luaL_addstring(B, s);
}
void luaL_addvalue(luaL_Buffer* B) {
    return LUA_FUNCTION_TABLE.luaL_addvalue(B);
}
void luaL_pushresult(luaL_Buffer* B) {
    return LUA_FUNCTION_TABLE.luaL_pushresult(B);
}
